name: Contributor Issue Form
description: Use this form to submit issues related to Med-o-Next
title: "[ISSUE]"
labels: ["needs triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to contribute to Med-o-Next! Please fill out the following fields to help us understand and address your issue effectively.

  - type: input
    id: issue_name
    attributes:
      label: "ISSUE NAME"
      description: "A short and descriptive title for your issue."
      placeholder: "e.g., Improve Med-o-Coach features"
    validations:
      required: true

  - type: input
    id: issue_branch
    attributes:
      label: "ISSUE BRANCH"
      description: "The Branch for which you are facing issue"
      placeholder: "e.g., Main, Med-o-Lens, Med-o-Shop, Med-o-Chat etc"
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: "ISSUE DESCRIPTION"
      description: "Provide a detailed description of the issue."
      placeholder: "Describe the problem, steps to reproduce, and any other relevant information."
    validations:
      required: true

  - type: textarea
    id: your_approach
    attributes:
      label: "YOUR APPROACH"
      description: "Describe how you plan to address this issue or implement the feature."
      placeholder: "e.g., I will optimize the diet prediction algorithm by..."
    validations:
      required: true

  - type: input
    id: your_name
    attributes:
      label: "YOUR NAME"
      description: "Your full name."
      placeholder: "e.g., John Doe"
    validations:
      required: true

  - type: input
    id: your_github_profile
    attributes:
      label: "YOUR GITHUB PROFILE URL"
      description: "Provide a link to your GitHub profile."
      placeholder: "https://github.com/YourUsername"
    validations:
      required: true
      pattern: '^https?://github\.com/.+'
      errorMessage: "Please enter a valid GitHub profile URL."

  - type: checkboxes
    id: issue_checkboxes
     validations:
      required: true
    attributes:
      label: "Please select the applicable categories"
      description: "Check the boxes that apply to your issue."
      options:
        - label: "Hacktoberfest"
        - label: "GSSOC'24 Extended"
        - label: "Read Documentation"
        - label: "Want more credentials"

  - type: markdown
    attributes:
      value: |
        ---
        Thank you for raising this issue! We will review your issue and get back to you shortly.
